FROM python:3.12-slim

WORKDIR /app

COPY backend/requirements-docker.txt .

RUN pip install --no-cache-dir \
    -i https://pypi.tuna.tsinghua.edu.cn/simple \
    --trusted-host pypi.tuna.tsinghua.edu.cn \
    --timeout 300 \
    --retries 10 \
    -r requirements-docker.txt

COPY backend/ .

EXPOSE 5000

CMD ["python", "run.py"]