"""make query document_id nullable

Revision ID: bfd539ad923e
Revises: 53b1fb88f824
Create Date: 2026-05-15 22:44:34.956509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd539ad923e'
down_revision = '53b1fb88f824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.alter_column('document_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.alter_column('document_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
